server:
  port: 11000

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: 1234

#  jpa:
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
#    open-in-view: false
#    hibernate:
#      ddl-auto: none

  docker:
    compose:
      lifecycle-management: start_only
      file: monitoring/compose.yaml

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: trace

