services:
  prometheus:
    image: 'prom/prometheus-linux-arm64'
    container_name: prometheus
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana
#    restart: always
    container_name: grafana
#    volumes:
#      - grafana_data:/var/lib/grafana
    ports:
      - '3000:3000'